---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure/main.yml

# - name: service
#   ansible.builtin.include_tasks: service.yml

# - name: test libvirt services
#   bodsch.kvm.libvirt_services:
#     units:
#       - libvirtd.socket
#       - libvirtd.service
#       - virtqemud.socket
#       - virtqemud.service
#   register: _monolitic
#   ignore_errors: true
#
# # - name: test modular daemons
# #   bodsch.kvm.libvirt_services:
# #     units:
# #       - virtqemud.socket
# #       - virtqemud.service
# #   register: _modular
# #   ignore_errors: true

...
