---

- name: handle virtual networks
  when:
    - libvirt_virtual_networks | default([]) | count > 0
  block:
    - name: modular services
      when:
        - libvirtd_version is version_compare("10", operator='>')
      block:
        - name: enable virtproxyd daemon
          bodsch.kvm.modular_services:
            state: enable
            units:
              - virtnetworkd.socket
          register: _service_states
          # ignore_errors: true
          notify:
            - daemon-reload

        - name: start virtproxyd socket
          bodsch.kvm.modular_services:
            state: start
            units:
              - virtnetworkd.socket
          register: _service_states
          notify:
            - daemon-reload

    - name: monolithic services
      when:
        - libvirtd_version is version_compare("10", operator='<')
      block:

        - name: enable / disable libvirtd-tcp.socket
          become: true
          ansible.builtin.service:
            name: libvirtd-tcp.socket
            enabled: "{{ 'true' if libvirt_libvirtd.enable_tcp else 'false' }}"
          failed_when: false
          notify:
            - restart libvirtd-tcp.socket
          when:
            - not ansible_check_mode
            - ansible_service_mgr | lower == "systemd"

        - name: enable / disable libvirtd-tls.socket
          become: true
          ansible.builtin.service:
            name: libvirtd-tls.socket
            enabled: "{{ 'true' if libvirt_libvirtd.enable_tls else 'false' }}"
          failed_when: false
          notify:
            - restart libvirtd-tls.socket
          when:
            - not ansible_check_mode
            - ansible_service_mgr | lower == "systemd"

    # wait for ...
    #  - /run/libvirt/virtnetworkd-sock

    - name: define virtual networks
      become: true
      community.libvirt.virt_net:
        command: define
        name: "{{ item.name }}"
        xml: "{{ lookup('template', 'etc/libvirt/qemu/networks/network.xml.j2') }}"
      when:
        - item.state is defined
        - not item.state | default("") == "absent"
      loop: "{{ libvirt_virtual_networks }}"
      loop_control:
        label: "{{ item.name }}"

    - name: setting state of virtual networks
      become: true
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      when:
        - item.state is defined
      loop: "{{ libvirt_virtual_networks }}"
      loop_control:
        label: "{{ item.name }}"

    - name: setting virtual networks to autostart
      become: true
      community.libvirt.virt_net:
        autostart: true
        name: "{{ item.name }}"
      when:
        - item.autostart is defined
        - item.autostart
        - item.state | default("") == "active"
      loop: "{{ libvirt_virtual_networks }}"
      loop_control:
        label: "{{ item.name }} - state: {{ item.state }}, autostart: {{ item.autostart }}"

    - name: remove virtual network from autostart
      become: true
      community.libvirt.virt_net:
        autostart: false
        name: "{{ item.name }}"
      failed_when: false
      when:
        - item.autostart is defined
        - not item.autostart or
          item.state | default("") in ["inactive","absent"]
      loop: "{{ libvirt_virtual_networks }}"
      loop_control:
        label: "{{ item.name }} - state: {{ item.state }}, autostart: {{ item.autostart }}"

...
